- name: make repo dir
  ansible.builtin.file:
    path: "{{ repo_dir }}"
    state: directory

- name: Create Ansible repository
  ansible.builtin.shell: "{{ create_repo }}"
  args:
    creates: "{{ repo_etc_file }}"
  notify:
  - add repo to etc
  - mkdir /etc/pulp/repo_type