---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    test_page: "http://{{ hostname }}:8080/pulp_ansible/galaxy/{{ base_path }}/api/v3/plugin/ansible/content/{{ base_path }}/collections/"
  tasks:
    - name: Replace this task with one that validates your content
      ansible.builtin.debug:
        msg: "This is the effective test"

    - name: View
      ansible.builtin.shell: "xdg-open {{ test_page }}"