---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    status_page: "http://localhost:8080/pulp/api/v3/status/"
    ansible_repo_page: "http://{{ hostname }}:8080/pulp_ansible/galaxy/{{ base_path }}/api/v3/plugin/ansible/content/{{ base_path }}/collections/"
    ansible_collection_page: "http://{{ hostname }}:8080/pulp_ansible/galaxy/{{ base_path }}/api/v3/plugin/ansible/content/{{ base_path }}/collections/index/"
  tasks:
    - name: Replace this task with one that validates your content
      ansible.builtin.debug:
        msg: "This is the effective test"

    - name: View
      ansible.builtin.shell: "xdg-open {{ item }}"
      loop:
      - "{{ status_page }}"
      - "{{ ansible_repo_page }}"