- name: Create directory for pulp podman-compose
  ansible.builtin.file:
    path: "{{ base_dir }}"
    state: directory

- name: git clone
  ansible.builtin.git:
    repo: "{{ git_url }}"
    dest: "{{ git_dir }}"