connect_cmd: "pulp config create --username admin --base-url http://{{ hostname }}:8080 --password {{ admin_password }}"  # from: https://pulpproject.org/pulp-in-one-container/#pulp-cli

cli_config_file: "~/.config/pulp/cli.toml"  # found with: `pulp config validate`